FROM node:16 AS production

#Working Dir - Container
WORKDIR /usr/src/app

#Copy source files
COPY . .

#Install modules
RUN npm i

#Compile typescript
RUN npm run build

#Expose the api port
EXPOSE 8000

CMD ["npm", "run", "start"]